// Equal invested ranks, deterministic control. Collision exposure is counted, HP loss disabled:
// this isolates damage/control/mechanics and MUST NOT be reported as human win rate.
const fs=require('node:fs'),assert=require('node:assert/strict'),Game=require('../game/core/Game'),Rules=require('../game/config/BuildConfig'),Random=require('../game/core/Random'),C=require('../game/config/GameConfig'),pilot=require('./sim_v190').pilot
require('../game/systems/GameLogger').enabled=false
const routes={precision:[['feather_blade',3],['tailwind',2],['sand_lance',3],['light_feather',3],['agile',3],['vitality',2],['regeneration',3]],missile:[['feather_blade',1],['missile_barrage',3],['missile_rack',3],['hunter_mark',2],['missile_link',2],['boss_slayer',2],['light_feather',3],['regeneration',3]],guard:[['feather_blade',3],['orbit_guard',3],['mirror_shield',2],['shield_burst',3],['toughness',3],['revenge_pulse',3],['vitality',2]],graze:[['feather_blade',3],['combo_heart',3],['phantom_edge',2],['echo_wing',3],['edge_focus',3],['light_feather',3],['vitality',2]],element:[['feather_blade',1],['frost_lance',3],['venom_thread',2],['storm_chain',3],['cinder_execution',3],['light_feather',3],['regeneration',3]],weather:[['feather_blade',1],['wind_rider',3],['storm_child',2],['wind_reader',3],['eye_of_storm',2],['light_feather',3],['regeneration',3]]}
// Normalize to 19 card ranks (including starter) by adding a legal non-offensive passive rank.
for(const entries of Object.values(routes)){let n=entries.reduce((s,x)=>s+x[1],0);if(n<19)entries.push(['physique',19-n])}
const rows=[]
for(const [route,entries] of Object.entries(routes))for(let ch=0;ch<6;ch++)for(const treatment of ['cards','specialization','evolution']){
 const g=new Game({},{},375,667,null);g.start();Random.seed(190+ch);g.chapterSystem._applyNextChapter(ch);g.chapterSystem._transition=null;g.abilitySystem.owned=new Map(entries);g.abilitySystem.refreshDerivedStats();g.build.specialization=treatment==='cards'?null:route;g.build.apex=treatment==='cards'?null:0;g.build.evolutions=treatment==='evolution'?[Rules.evolutions.find(e=>e.route===route).id]:[]
 const size=g.abilitySystem.owned.size,components=entries.filter(([id])=>Rules.components.includes(id)).length;assert.ok(components<=3&&size-components<=6);assert.equal(entries.reduce((s,x)=>s+x[1],0),19)
 g._spawnBoss();g.chapterSystem.startBossFight();g.boss._setState('roam');g.boss.x=g.boss.homeX;const boss=g.boss;g.expSystem.addExp=()=>0
 let exposure=0,maxHazards=0;g._handleCollision=()=>{exposure++;return false};g._buildGameCtx=(()=>{const original=g._buildGameCtx.bind(g);return()=>{const ctx=original();ctx.isVictoryProtected=()=>true;return ctx}})()
 const p={last:-99,pending:-1,observe:0,target:300,daze:0};let seed=190;const random=()=>((seed=Math.imul(seed,1664525)+1013904223)>>>0)/4294967296
 for(let i=0;i<C.BOSS.VARIANTS[ch].survivalFrames+60&&g.state==='playing';i++){pilot(g,p,random);g.update();maxHazards=Math.max(maxHazards,g.feathers.length)}
 rows.push({route,treatment,chapter:ch+1,method:g.bossClears[0]?.method||'unfinished',seconds:g.bossFightFrames/60,damage:boss.damageLog,exposureFrames:exposure,maxHazards,mechanics:boss.mechanics.events,events:g.build.events.map(e=>e.type)})
}
fs.writeFileSync('docs/audits/v190/boss-matrix.json',JSON.stringify({protocol:'19 card ranks; cards-only / specialization+branch / specialization+branch+evolution treatments. Fixed imperfect pilot; HP loss disabled, collision exposure logged. No human win-rate claim.',rows},null,2)+'\n');console.log(rows.map(r=>`${r.route}/${r.treatment} Ch${r.chapter} ${r.method} ${r.seconds.toFixed(1)}s hit ${r.damage.applied} exposure ${r.exposureFrames}`).join('\n'))
