const assert=require('node:assert/strict'),fs=require('node:fs'),Game=require('../game/core/Game'),R=require('../game/abilities/AbilityRegistry'),Rules=require('../game/config/BuildConfig'),Random=require('../game/core/Random'),Art=require('../game/art/GameArt'),Hazard=require('../game/entities/BossHazard'),C=require('../game/config/GameConfig')
require('../game/systems/GameLogger').enabled=false
const memory=new Map();global.wx={getStorageSync:k=>memory.get(k),setStorageSync:(k,v)=>memory.set(k,JSON.parse(JSON.stringify(v))),removeStorageSync:k=>memory.delete(k)}
let count=0;const results=[]
function test(name,fn){try{fn();count++;results.push({name,passed:true});console.log('✓ '+name)}catch(e){results.push({name,passed:false,error:e.message});console.error('✗ '+name+'\n'+e.stack);process.exitCode=1}}
function make(){const g=new Game({},{},375,667,null);g.start();Random.seed(190);g.bird.y=300;return g}
function equip(g,entries){g.abilitySystem.owned=new Map(entries);g.abilitySystem.chapter=5;g.abilitySystem.refreshDerivedStats()}
function fight(ch=0){const g=make();g.chapterSystem._applyNextChapter(ch);g.chapterSystem._transition=null;g._spawnBoss();g.chapterSystem.startBossFight();g.boss.x=g.boss.homeX;g.boss._setState('roam');g.boss.mechanics.cycleStart();return g}
function panel(g){g.expSystem.pendingLevelUps=2;g._triggerLevelUp();g._choiceOpenedAt=0;g._choiceViewport={x:0,y:100,w:375,h:400};g._cardBounds=[{x:16,y:100,w:343,h:100,id:g._currentChoices[0].id}];g._confirmBounds={x:120,y:530,w:239,h:44};g._rerollBounds={x:16,y:530,w:94,h:44}}
function tap(g,x,y){Art.touchStart(g,x,y);Art.touchEnd(g,x,y)}
test('73卡逐项迁移：11组件、60被动、2基础UI，等级与合法获取',()=>{const cards=R.getAll();assert.equal(cards.length,73);assert.equal(cards.filter(d=>d.slotType==='component').length,11);assert.equal(cards.filter(d=>!d.retired&&d.slotType==='passive').length,60);for(const d of cards){assert.equal(d.maxLevel,Math.min(3,d.legacyMaxLevel));assert.ok(d.sourceTags.length);const g=make();equip(g,[]);g.abilitySystem.chapter=Math.max(5,d.unlockChapter);for(const id of d.prerequisiteAny)if(!g.abilitySystem.owned.size)g.abilitySystem.selectAbility(id);for(let i=0;i<d.maxLevel+2;i++)g.abilitySystem.selectAbility(d.id);assert.equal(g.abilitySystem.owned.get(d.id)||0,d.retired?0:d.maxLevel,d.id)}})
test('三组件六被动硬上限，所有抽卡路径不能越界/重复/新添第十卡',()=>{const g=make();equip(g,[['feather_blade',2],['orbit_guard',2],['missile_barrage',2],['tailwind',2],['lucky',3],['light_feather',2],['agile',2],['vitality',1],['regeneration',2]]);for(let i=0;i<200;i++){const choices=g.build.choices(i%2===0);assert.equal(new Set(choices.map(c=>c.id)).size,choices.length);for(const d of choices)assert.ok(g.abilitySystem.owned.has(d.id)||d.id.startsWith('evo_'));}g.abilitySystem.selectAbility('magnet');g.abilitySystem.selectAbility('frost_lance');assert.equal(g.abilitySystem.owned.size,9)})
test('普通保底核心，2次重掷不推进保底，普通升级后至少6秒',()=>{const g=make();panel(g);assert.ok(g._currentChoices.some(d=>d.id==='feather_blade'));const n=g.build.panels;assert.ok(g.rerollChoices());assert.ok(g.rerollChoices());assert.equal(g.rerollChoices(),false);assert.equal(g.build.panels,n);assert.ok(g.selectAbility(g._currentChoices[0].id));assert.equal(g.expSystem.pendingLevelUps,1);assert.equal(g._nextChoiceAt,g.gameTime+360)})
test('幸运六卡只预选；350ms开窗锁、250ms确认锁、固定按钮提交',()=>{const g=make();equip(g,[['feather_blade',1],['lucky',3]]);panel(g);assert.equal(g._currentChoices.length,6);const id=g._currentChoices[0].id,n=g.abilitySystem.owned.get(id)||0;g._choiceOpenedAt=Date.now();tap(g,40,140);assert.equal(g._choiceSelected,null);g._choiceOpenedAt=0;tap(g,40,140);assert.equal(g._choiceSelected,id);assert.equal(g.abilitySystem.owned.get(id)||0,n);tap(g,180,550);assert.equal(g.state,'upgrading');g._choiceSelectedAt=0;tap(g,180,550);assert.equal(g.state,'playing');assert.equal(g.abilitySystem.owned.get(id),n+1)})
test('滑动/取消/跨面板/按住拍翅时弹窗/双击均不误选',()=>{const g=make();panel(g);Art.touchStart(g,40,140);Art.touchMove(g,40,180);Art.touchEnd(g,40,140);assert.equal(g._choiceSelected,null);Art.touchStart(g,40,140);g.handleTouchCancel();Art.touchEnd(g,40,140);assert.equal(g._choiceSelected,null);Art.touchStart(g,40,140);g._triggerLevelUp();Art.touchEnd(g,40,140);assert.equal(g._choiceSelected,null);g.state='playing';Art.touchStart(g,40,140);panel(g);Art.touchEnd(g,40,140);assert.equal(g._choiceSelected,null);tap(g,40,140);tap(g,40,140);assert.equal(g.state,'upgrading')})
test('进化最多2项，同核互斥，不加槽；临时等级不能解锁永久进化',()=>{const g=make();equip(g,[['feather_blade',3],['tailwind',2],['orbit_guard',3],['mirror_shield',2],['wind_rider',3],['storm_child',2]]);assert.ok(g.build.apply('evo_precision_pierce'));assert.equal(g.build.apply('evo_precision_fan'),false);assert.equal(g.build.apply('evo_guard_evolved'),false);g.chapterSystem.index=3;assert.ok(g.build.apply('evo_guard_evolved'));assert.equal(g.build.apply('evo_weather_evolved'),false);assert.equal(g.abilitySystem.owned.size,6);g.build.evolutions=[];g._echoBoost={id:'feather_blade',from:2,to:3};assert.equal(g.build.availableEvolutions().some(e=>e.route==='precision'),false)})
test('换装完整事务：依赖可一起换、拒绝单独卸前置、已用复活/顿悟不重置',()=>{const g=make();equip(g,[['feather_blade',3],['tailwind',2],['phoenix',2]]);g.build.specialization='precision';g.build.evolutions=['evo_precision_pierce'];g._panelMode='rest';assert.equal(g.build.previewReplacement([{from:'feather_blade',to:'orbit_guard',level:3}],'guard').ok,false);const p=g.build.previewReplacement([{from:'feather_blade',to:'orbit_guard',level:3},{from:'tailwind',to:'mirror_shield',level:2}],'guard');assert.ok(p.ok);g.abilitySystem.phoenixUsed=2;g.expSystem.enlightenUsed=3;g._panelMode='adjustConfirm';assert.ok(g.build.replace(p));assert.equal(g.build.refund,1);assert.equal(g.build.evolutions.length,0);assert.equal(g.build.adjustments,1);assert.equal(g.abilitySystem.phoenixUsed,2);assert.equal(g.expSystem.enlightenUsed,3);assert.equal(g.build.specialization,'guard')})
test('换装可重新分配两张卡的总投资、无效事务不扣资源',()=>{const g=make();equip(g,[['feather_blade',3],['tailwind',1]]);g._panelMode='rest';const p=g.build.previewReplacement([{from:'feather_blade',to:'orbit_guard',level:2},{from:'tailwind',to:'mirror_shield',level:2}],'guard');assert.ok(p.ok);const bad=g.build.previewReplacement([{from:'feather_blade',to:'orbit_guard',level:1}]);assert.equal(bad.ok,false);assert.equal(g.build.adjustments,2);assert.equal(g.abilitySystem.owned.get('feather_blade'),3)})
test('换装旧章间卡不阻挡末章调整，卸下效果撤销且不回血',()=>{const g=make();equip(g,[['feather_blade',1],['nomad',1],['vitality',2]]);g.abilitySystem.chapter=6;g.abilitySystem.hp=1;g._panelMode='rest';const p=g.build.previewReplacement([{from:'vitality',to:'physique',level:2}]);assert.ok(p.ok);assert.ok(g.build.replace(p));assert.equal(g.abilitySystem.hp,1);assert.equal(g.abilitySystem.maxHp,C.HP.INITIAL_MAX)})
test('章节之主提前且下次兑现，重掷保留稀有保证，末章过滤未来收益卡',()=>{const g=make();g.abilitySystem.chapter=2;g.build.apply('chapter_master');assert.ok(g.build.choices().some(c=>c.rarity==='epic'));assert.ok(g.build.choices(true).some(c=>c.rarity==='epic'));g.abilitySystem.chapter=6;for(let i=0;i<100;i++)assert.ok(g.build.choices().every(c=>!['nomad','chapter_echo','oracle','pipe_sense'].includes(c.id)))})
test('满配有限突破后只补给，绝不all_buff无限增长',()=>{const g=make();equip(g,[['feather_blade',3],['orbit_guard',3],['shield_burst',3],['light_feather',3],['agile',3],['magnet',3],['greed',3],['double_score',3],['physique',3]]);for(let i=0;i<9;i++){const d=g.build.choices()[0];assert.ok(d.id.startsWith('boost_'));assert.ok(g.build.apply(d.id))}assert.equal(g.build.choices()[0].id,'supply');assert.equal(g.build.apply('boost_feather_blade'),false)})
test('齐射按批次预算真实增伤，限幅可观测，下一批立即可伤害',()=>{const g=fight(),b=g.boss;b.mechanics.damageScale=()=>1;let hp=b.hp;for(let i=0;i<4;i++)b.takeDamage(4,'missile',1);assert.equal(hp-b.hp,16);for(let i=0;i<4;i++)b.takeDamage(4,'missile',1);assert.equal(b.damageLog.applied,24);assert.ok(b.damageLog.limited>0);hp=b.hp;b.takeDamage(4,'missile',2);assert.equal(hp-b.hp,4)})
test('派生伤害不复射/挂毒/递归连锁，组件节奏白名单',()=>{const g=make();equip(g,[['feather_blade',3],['frost_lance',3],['tailwind',3],['shadow_echo',3],['venom_thread',3]]);for(let i=0;i<12;i++)g.combat.fire(2,2,[0],'echo');assert.equal(g.combat.shots.length,Math.min(12,C.COMBAT.MAX_BLADES));assert.equal(g.combat.castCount,0);assert.ok(g.combat.cadence('feather_blade')<1);assert.equal(g.combat.cadence('frost_lance'),1)})
test('守卫不能挡穿盾或区域；镜盾拦截蓄层产生反击',()=>{const g=make();equip(g,[['orbit_guard',3],['mirror_shield',2]]);const p={x:g.bird.x,y:g.bird.y,age:100,warn:0,radius:5,piercing:true};assert.equal(g.combat.intercept(p),false);p.piercing=false;p.kind='beam';assert.equal(g.combat.intercept(p),false);p.kind='bolt';assert.ok(g.combat.intercept(p));g.combat.guardCD=0;assert.ok(g.combat.intercept(p));assert.ok(g.build.events.some(e=>e.type==='guard'))})
test('擦边进化用真实过管/擦边充能，受伤断连，个人风窗不生天气实体',()=>{const g=make();equip(g,[['feather_blade',3],['combo_heart',3],['phantom_edge',2],['wind_rider',3],['storm_child',2]]);g.build.evolutions=['evo_graze_evolved'];g.combat.onGraze();assert.equal(g.combat.grazeCharge,3);g.combat.onGraze();assert.equal(g.combat.grazeWindow,180);g.combat.updateCampaign();assert.ok(g.combat.windWindow>0);assert.equal(g.weatherSystem.activeEffects.length,0)})
test('草地根源独立永久破坏；夜卵分别封路与追踪且数量有界',()=>{let g=fight(0),m=g.boss.mechanics;m.nodes[0].takeDamage(999,'blade');assert.ok(m.nodes[0].hp===0&&m.nodes[1].hp>0);for(let i=0;i<1000;i++)m.update(g.bird);assert.equal(m.nodes.length,2);g=fight(2);m=g.boss.mechanics;for(let i=0;i<421;i++)m.update(g.bird);assert.ok(g.feathers.some(h=>h.kind==='beam'));assert.ok(g.feathers.some(h=>h.target===g.bird));assert.equal(m.nodes.length,2)})
test('冰川3秒蓄热，离开0.8秒保留，永久碎冰，不再45帧换边',()=>{const g=fight(3),m=g.boss.mechanics;for(let i=0;i<90;i++){g.bird.y=m.zoneY;m.update(g.bird)}assert.equal(m.completed,0);const p=m.zoneTime;g.bird.y=0;for(let i=0;i<48;i++)m.update(g.bird);assert.equal(m.zoneTime,p);m.update(g.bird);assert.ok(m.zoneTime<p);for(let i=0;i<100;i++){g.bird.y=m.zoneY;m.update(g.bird)}assert.equal(m.completed,1);assert.ok(m.weak>0)})
test('火山开窗已在区内不触发，须离开再进入；一轮一个；瞬移不触发',()=>{const g=fight(4),m=g.boss.mechanics,v=m.valves[0];g.bird.y=v.y;for(let i=0;i<100;i++)m.update(g.bird);assert.equal(m.valveChosen,false);g.bird.y=v.y+60;m.update(g.bird);g.bird.y=v.y;g.bird.teleportGrace=30;m.update(g.bird);assert.equal(m.valveChosen,false);g.bird.teleportGrace=0;g.bird.y=v.y+60;m.update(g.bird);g.bird.y=v.y;m.update(g.bird);assert.ok(m.valveChosen);assert.ok(m.cancelEruption);const n=m.events.length;g.bird.y=m.valves[1].y;m.update(g.bird);assert.equal(m.events.length,n)})
test('风暴未来节点不吸弹，范围不能跳序；追踪按玩家高度选夜卵',()=>{const g=fight(5),m=g.boss.mechanics;assert.deepEqual(g.combat.targets().filter(t=>t.isMechanic),[m.nodes[0]]);m.nodes[1].takeDamage(999,'blade');assert.ok(m.nodes[1].hp>0);m.nodes[0].takeDamage(999,'magma');assert.ok(m.nodes[0].hp>0);m.nodes[0].takeDamage(999,'blade');assert.equal(m.activeNode,1);const n=fight(2);n.bird.y=n.boss.mechanics.nodes[1].y;assert.equal(n.combat.chooseTarget(),n.boss.mechanics.nodes[1])})
test('沙漠锁定后不追身，P2在55%时间而非35%',()=>{const g=fight(1),b=g.boss;b._beginAttack(g.bird);assert.equal(b.state,'windup');for(let i=0;i<120;i++)b.update(g.bird,i);const y=b.chargeY;g.bird.y+=100;for(let i=0;i<30;i++)b.update(g.bird,121+i);assert.equal(b.chargeY,y);const q=fight(3);q.boss.update(q.bird,q.boss.survivalFrames*.36);assert.equal(q.boss.phase,1);q.boss.update(q.bird,q.boss.survivalFrames*.56);assert.equal(q.boss.phase,2)})
test('Boss只一项成长，第一/第三章专精，末章主动结束/无尽',()=>{for(const method of ['kill','survival']){const g=fight();const level=g.expSystem.level;g._onBossVictory(method);for(let i=0;i<31;i++)g.update();assert.equal(g._panelMode,'bossGrowth');assert.equal(g.expSystem.level,level);g.selectAbility(g._currentChoices[0].id);assert.equal(g._panelMode,'specialization');g.selectAbility(g._currentChoices[0].id);assert.equal(g._panelMode,'rest');g.selectAbility('rest_continue');assert.equal(g.state,'playing')}
 const g=fight(5);g.chapterSystem.cleared=new Set([0,1,2,3,4]);g.build.specialization='precision';g.build.apex=0;g._startBossRewards();g.selectAbility(g._currentChoices[0].id);assert.ok(g._currentChoices.some(d=>d.id==='rest_finish'));g.selectAbility('rest_continue');assert.ok(g.chapterSystem.endless)
 const h=fight(5);h.chapterSystem.cleared=new Set([0,1,2,3,4]);h._bossRewardPending=true;h._openRest();h.selectAbility('rest_finish');assert.equal(h.report.victory,true);assert.equal(h.report.chapters,6)
})
test('存档恢复原候选/随机/待选/一次性资源，恢复不重新发奖',()=>{const g=fight();g.expSystem.pendingLevelUps=4;g.abilitySystem.phoenixUsed=1;g.expSystem.enlightenUsed=2;g._startBossRewards();const ids=g._currentChoices.map(c=>c.id),score=g.score,random=Random.getState();assert.ok(g._saveCheckpoint());const h=new Game({},{},375,667,null);assert.ok(h.resumeRun());assert.equal(h.score,score);assert.equal(h.expSystem.pendingLevelUps,4);assert.equal(h.abilitySystem.phoenixUsed,1);assert.equal(h.expSystem.enlightenUsed,2);assert.deepEqual(h._currentChoices.map(c=>c.id),ids);assert.equal(Random.getState(),random);assert.ok(require('../utils/Storage').loadRun());h.selectAbility(ids[0]);const j=new Game({},{},375,667,null);assert.ok(j.resumeRun());assert.equal(j._panelMode,'specialization');assert.equal(j.score,score)})
test('旧规则存档拒绝；当前存档恢复天气原型，冰雹实体可继续更新',()=>{const Storage=require('../utils/Storage');Storage.saveRun({version:'1.8.6'});assert.equal(new Game({},{},375,667,null).resumeRun(),false);const g=fight();const H=require('../game/weather/HailEffect'),e=new H();e.onTrigger(g._buildGameCtx());e._spawnHailstone(375);g.weatherSystem.activeEffects=[e];g._startBossRewards();const h=new Game({},{},375,667,null);assert.ok(h.resumeRun());assert.equal(typeof h.weatherSystem.activeEffects[0].update,'function');assert.equal(typeof h.weatherSystem.activeEffects[0].hailstones[0].update,'function')})
test('30/60/120fps推进相同60Hz物理，后台不偷跑/无追帧突死',()=>{for(const fps of [30,60,120]){const g=make();let ticks=0;g.update=()=>ticks++;g.advanceClock(0);for(let i=1;i<=fps*10;i++)g.advanceClock(i*1000/fps);assert.equal(ticks,600);g.suspend(10000);g.advanceClock(20000);assert.equal(ticks,600);g.resume(20000);g.advanceClock(20000);g.advanceClock(20000+1000/fps);assert.ok(ticks<=602);assert.equal(g.timings.pause,10)}})
test('训练靶只发一次奖励，不刷收割/掉落/杀怪计数',()=>{const g=make();g.gameTime=480;g._updateTraining();const m=g.monsters.find(m=>m.training);assert.ok(m);assert.equal(m.checkCollision(g.bird),false);g._onMonsterKilled(m);const exp=g.expSystem.exp;g._onMonsterKilled(m);assert.equal(g.expSystem.exp,exp);assert.equal(g.monsterKills,0);assert.equal(g.combat.harvestKills,0)})
test('六章时间配置与阶段独立计时',()=>{assert.deepEqual(C.CHAPTERS.LIST.map(c=>c.minFrames/60),[90,95,100,105,110,115]);assert.deepEqual(C.BOSS.VARIANTS.map(c=>c.survivalFrames/60),[55,60,65,70,75,80]);const g=make();g.update();assert.ok(g.timings.flight>0);g._triggerLevelUp();g.update();assert.ok(g.timings.reading>0);assert.equal(g.gameTime,1)})
test('章节成长额度只延后释放，不丢XP；退款和无尽不被卡住',()=>{const g=make();g.build.growthInvestments=7;g.expSystem.pendingLevelUps=20;assert.equal(g.build.canReleaseGrowth(),false);g.chapterSystem.index=1;assert.equal(g.build.canReleaseGrowth(),true);assert.equal(g.expSystem.pendingLevelUps,20);g.build.growthInvestments=100;g.chapterSystem.endless=true;assert.ok(g.build.canReleaseGrowth())})
test('完整换装UI同时换核心/前置/专精，确认后只消耗一次',()=>{const g=make();equip(g,[['feather_blade',3],['tailwind',2]]);g.build.specialization='precision';g.build.evolutions=['evo_precision_pierce'];g._bossRewardPending=true;g._openRest();for(const id of ['rest_adjust','from_feather_blade','to_orbit_guard','from_tailwind','to_mirror_shield','spec_guard','adjust_apply'])assert.notEqual(g.selectAbility(id),false,id);assert.equal(g._panelMode,'rest');assert.equal(g.build.specialization,'guard');assert.equal(g.build.adjustments,1);assert.equal(g.build.refund,1)})
test('无适用专精的换装仍能取消返回，不出现空面板',()=>{const g=make();g.build.specialization='precision';g._bossRewardPending=true;g._openRest();for(const id of ['rest_adjust','from_feather_blade','to_shield_burst','adjust_done'])g.selectAbility(id);assert.equal(g._panelMode,'adjustSpec');assert.ok(g.selectAbility('adjust_cancel'));assert.equal(g._panelMode,'rest');assert.equal(g.build.adjustments,2)})
test('个人风窗不提高天气经验、移出驯化再装回不重抽天气',()=>{const g=make();equip(g,[['feather_blade',1],['wind_rider',1],['storm_child',1],['eye_of_storm',2],['chaos_dice',1]]);g.abilitySystem.chapter=6;g.abilitySystem.personalWind=true;assert.equal(g.abilitySystem.getStats().expMultiplier,1);assert.ok(g.abilitySystem.getStats().scoreMultiplier>1);g._panelMode='rest';g.build.tamingUsed=true;g.weatherSystem.tamedWeather='rain';assert.ok(g.build.replace(g.build.previewReplacement([{from:'chaos_dice',to:'magnet',level:1}])));assert.equal(g.weatherSystem.tamedWeather,null);assert.ok(g.build.replace(g.build.previewReplacement([{from:'magnet',to:'chaos_dice',level:1}])));assert.equal(g.weatherSystem.tamedWeather,'rain')})
test('升级清弹组件不会抹掉穿盾/区域危险，Boss不被时晶硬冻结',()=>{const g=fight(3);equip(g,[['feather_blade',1],['frost_shell',3]]);const beam=new Hazard({kind:'beam',x:g.bird.x,y:g.bird.y,age:100,warn:0,piercing:true}),bolt=new Hazard({x:g.bird.x,y:g.bird.y,age:100,warn:0});g.feathers=[beam,bolt];g.combat.updateCampaign();assert.deepEqual(g.feathers,[beam]);g.abilitySystem.timeCrystalFreezeFrames=120;const t=g.boss.stateT;for(let i=0;i<4;i++)g._updateBossFight(3);assert.ok(g.boss.stateT>t)})
test('新旧最高分独立保存，历史分数不丢弃',()=>{const Storage=require('../utils/Storage');memory.set('snappy_best_score',9999);Storage.saveBestScore(123);assert.equal(Storage.getBestScore(),123);assert.equal(Storage.getLegacyBestScore(),9999)})
fs.mkdirSync('docs/audits/v190',{recursive:true});fs.writeFileSync('docs/audits/v190/regression-results.json',JSON.stringify({version:C.VERSION,passed:count,total:results.length,results},null,2)+'\n');console.log(`${count}/${results.length} passed`)
